version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: '{asctime} {levelname} {name} {message}'
    style: '{'
handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: simple
  file_debug:
    level: DEBUG
    class: logging.handlers.RotatingFileHandler
    mode: w
    formatter: simple
    filename: logs/notifier_debug.log
    maxBytes: 5242880
    backupCount: 3
loggers:
  __main__:
    handlers:
      - console
      - file_debug
    level: DEBUG
  notifier.notify:
    handlers:
      - file_debug
    level: DEBUG
  notifier.rule:
    handlers:
      - file_debug
    level: DEBUG
