version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: '{asctime} - {levelname} - {name} >> {message}'
    style: '{'
handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: simple
  file_error:
    level: ERROR
    class: logging.handlers.RotatingFileHandler
    mode: a
    formatter: simple
    filename: logs/notifier_error.log
    maxBytes: 1024
    backupCount: 3
  file_info:
    level: INFO
    class: logging.handlers.RotatingFileHandler
    mode: a
    formatter: simple
    filename: logs/notifier_info.log
    maxBytes: 1024
    backupCount: 3
  file_debug:
    level: DEBUG
    class: logging.FileHandler
    mode: w
    formatter: simple
    filename: logs/notifier_debug.log
loggers:
  __main__:
    handlers:
      - file_error
      - file_info
      - file_debug
    level: DEBUG
  notifier.notify:
    handlers:
      - file_error
      - file_info
      - file_debug
    level: DEBUG
